name: run-clang-format
run-name: run format_code.sh
on: 
  push:
    paths:
      - '**.java'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        name: Add repostory to safe.directory
      - run: bash format_code.sh
